import type { Metadata } from 'next';
import localFont from 'next/font/local';
import './globals.css';
import './fonts/WEB/css/satoshi.css';

const satoshi = localFont({
  src: [
    {
      path: './fonts/WEB/fonts/Satoshi-Variable.woff2',
      weight: '100 900',
      style: 'normal',
    },
  ],
  variable: '--font-satoshi',
  display: 'swap',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${satoshi.variable} antialiased`}>{children}</body>
    </html>
  );
}
